version: '3'
services:
  showcase-database:
    container_name: showcase-database
    image: postgres
    ports:
      - ${SHOWCASE_DB_PORT}:${SHOWCASE_DB_PORT}
    environment:
      - POSTGRES_USER=${SHOWCASE_DB_USER}
      - POSTGRES_PASSWORD=${SHOWCASE_DB_PASS}
      - POSTGRES_DB=${SHOWCASE_DB_NAME}
    volumes:
      - showcase-database-data:/var/lib/postgresql/data
    networks:
      - showcase-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SHOWCASE_DB_USER} -d ${SHOWCASE_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
  showcase-backend:
    container_name: showcase-backend
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - ${SHOWCASE_BACKEND_PORT}:${SHOWCASE_BACKEND_PORT}
    environment:
      - SHOWCASE_DB_USER=${SHOWCASE_DB_USER}
      - SHOWCASE_DB_PASS=${SHOWCASE_DB_PASS}
      - SHOWCASE_DB_NAME=${SHOWCASE_DB_NAME}
      - SHOWCASE_DB_HOST=showcase-database
      - SHOWCASE_DB_PORT=${SHOWCASE_DB_PORT}
      - SHOWCASE_FRONTEND_HOST=${SHOWCASE_FRONTEND_HOST}
      - SHOWCASE_FRONTEND_PORT=${SHOWCASE_FRONTEND_PORT}
    depends_on:
      - showcase-database
    networks:
      - showcase-net
    command: bash -c "alembic upgrade head && uvicorn backend.app.main.routes:app --host 0.0.0.0 --port 8000"
  showcase-frontend:
    container_name: showcase-frontend
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - ${SHOWCASE_FRONTEND_PORT}:80
    environment:
      - VUE_APP_SHOWCASE_API_BASE_URL=${VUE_APP_SHOWCASE_API_BASE_URL}
      - VUE_APP_SHOWCASE_FALLBACK_API_BASE_URL=${VUE_APP_SHOWCASE_FALLBACK_API_BASE_URL}
    depends_on:
      - showcase-backend
    networks:
      - showcase-net
volumes:
  showcase-database-data:
  showcase-backend-data:

networks:
  showcase-net:
    driver: bridge
